# Generated by Django 2.1.2 on 2018-11-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181115_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinblog',
            name='the_sub',
            field=models.CharField(default='None', max_length=150, null=True),
        ),
    ]
