# Generated by Django 2.1.3 on 2018-11-17 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_Id', models.CharField(max_length=100)),
                ('Spec', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('D_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Avail', models.BooleanField(blank=True)),
                ('Phone', models.IntegerField(blank=True, default=0)),
                ('gender', models.CharField(blank=True, default='Male', max_length=10)),
                ('Degrees', models.CharField(blank=True, max_length=250)),
                ('Latitudes', models.IntegerField(blank=True, default=0)),
                ('Longitudes', models.IntegerField(blank=True, default=0)),
                ('Desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=250)),
                ('Phone1', models.IntegerField(null=True)),
                ('H_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='H_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='welcome.Hospital_Details'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='T_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='welcome.Doctor_Type'),
        ),
    ]
