# Generated by Django 2.1.3 on 2018-11-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20181117_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='license',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
