# Generated by Django 2.1.3 on 2018-11-26 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('welcome', '0004_auto_20181118_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(max_length=3)),
                ('emerg_email', models.CharField(blank=True, max_length=13)),
                ('Gender', models.CharField(max_length=10)),
                ('Blood_group', models.CharField(max_length=3)),
                ('medical_con', models.CharField(default='None', max_length=300)),
                ('image_url', models.CharField(default='', max_length=400)),
                ('user_ava', models.CharField(default='no', max_length=4)),
                ('Phone_num', models.CharField(blank=True, max_length=13)),
                ('Emergency_num', models.CharField(blank=True, max_length=13)),
                ('P_Id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
