# Generated by Django 2.1.3 on 2018-11-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_patient_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_db',
            old_name='user_ava',
            new_name='user_pat',
        ),
        migrations.AddField(
            model_name='doctors',
            name='user_pat',
            field=models.CharField(default='no', max_length=4),
        ),
    ]
