# Generated by Django 2.1.3 on 2018-12-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0008_auto_20181202_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Latitudes',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Longitudes',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
    ]
