# Generated by Django 2.1.3 on 2018-12-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0008_auto_20181202_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=10)),
                ('slots', models.IntegerField()),
                ('D_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='welcome.Doctors')),
                ('P_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='welcome.Patient_DB')),
            ],
        ),
    ]
