# Generated by Django 2.1.3 on 2018-12-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0009_auto_20181207_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doc_type',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
