# Generated by Django 2.1.3 on 2018-12-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0011_doctors_d_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='About_Clinic',
            field=models.TextField(blank=True, default='Its good', max_length=300),
        ),
    ]
