# Generated by Django 2.1.3 on 2018-12-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0009_appointment'),
        ('welcome', '0013_doctors_other_info'),
    ]

    operations = [
    ]
