# Generated by Django 2.1.3 on 2018-12-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0014_merge_20181209_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='About_Clinic',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='T_Id',
        ),
        migrations.AddField(
            model_name='doctors',
            name='Spec',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Latitudes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Longitudes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.DeleteModel(
            name='Doctor_Type',
        ),
    ]
