# Generated by Django 2.1.3 on 2018-12-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0015_auto_20181209_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='About_Clinic',
            field=models.TextField(blank=True, default='Its good', max_length=300),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
