# Generated by Django 2.1.3 on 2018-12-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0016_auto_20181209_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Latitudes',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Longitudes',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='patient_db',
            name='Phone_num',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='patient_db',
            name='emerg_email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
