# Generated by Django 2.1.2 on 2018-12-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0017_auto_20181209_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Latitudes',
            field=models.FloatField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Longitudes',
            field=models.FloatField(blank=True, default=0, max_length=30),
        ),
    ]
