# Generated by Django 2.1.2 on 2018-12-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0020_auto_20181210_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doc_info',
            field=models.TextField(blank=True, default='Edit your info in Profile Manager'),
        ),
    ]
