# Generated by Django 2.1.2 on 2018-11-15 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_avail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_grp', models.CharField(max_length=255)),
                ('Availability', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Blood_Bank',
            fields=[
                ('BB_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('BB_name', models.CharField(max_length=255)),
                ('Lat', models.FloatField(default='NULL')),
                ('Long', models.FloatField(default='NULL')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_Id', models.CharField(max_length=100)),
                ('Spec', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avail', models.BooleanField(blank=True)),
                ('Phone', models.IntegerField(blank=True, default=0)),
                ('Degrees', models.CharField(blank=True, max_length=250)),
                ('Latitudes', models.IntegerField(blank=True, default=0)),
                ('Longitudes', models.IntegerField(blank=True, default=0)),
                ('Desc', models.TextField(blank=True)),
                ('D_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='General_Medicine',
            fields=[
                ('Disease', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Medicine', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=250)),
                ('Phone1', models.IntegerField()),
                ('Phone2', models.IntegerField()),
                ('Phone3', models.IntegerField()),
                ('H_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_shop',
            fields=[
                ('shop_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=255)),
                ('Lattitude', models.FloatField(default='NULL')),
                ('Longitude', models.FloatField(default='NULL')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Blood_group', models.CharField(max_length=3)),
                ('Marital_Status', models.CharField(max_length=3)),
                ('Phone_num', models.IntegerField()),
                ('Emergency_num', models.IntegerField()),
                ('P_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Med_id', models.CharField(max_length=255)),
                ('Medicine_name', models.CharField(max_length=255)),
                ('Stock', models.IntegerField()),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Medical_shop')),
            ],
        ),
        migrations.CreateModel(
            name='textinblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_text', models.TextField()),
                ('the_sub', models.TextField(blank=True, default='None', null=True)),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='H_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Hospital_Details'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='T_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Doctor_Type'),
        ),
        migrations.AddField(
            model_name='blood_avail',
            name='BB_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Blood_Bank'),
        ),
    ]
