# Generated by Django 2.1.2 on 2018-12-11 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181211_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_avail',
            name='BB_id',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='D_Id',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='H_Id',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='T_Id',
        ),
        migrations.DeleteModel(
            name='General_Medicine',
        ),
        migrations.RemoveField(
            model_name='hospital_details',
            name='H_Id',
        ),
        migrations.RemoveField(
            model_name='patient_db',
            name='P_Id',
        ),
        migrations.RemoveField(
            model_name='stock_availability',
            name='shop_id',
        ),
        migrations.DeleteModel(
            name='Tips',
        ),
        migrations.AlterField(
            model_name='textinblog',
            name='doctors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='welcome.Doctors'),
        ),
        migrations.DeleteModel(
            name='Blood_avail',
        ),
        migrations.DeleteModel(
            name='Blood_Bank',
        ),
        migrations.DeleteModel(
            name='Doctor_Type',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.DeleteModel(
            name='Hospital_Details',
        ),
        migrations.DeleteModel(
            name='Medical_shop',
        ),
        migrations.DeleteModel(
            name='Patient_DB',
        ),
        migrations.DeleteModel(
            name='Stock_availability',
        ),
    ]
