# Generated by Django 2.1.3 on 2018-11-16 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_Name', models.CharField(max_length=50)),
                ('L_Name', models.CharField(max_length=50)),
                ('Degrees', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_Id', models.CharField(max_length=100)),
                ('Spec', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('D_Id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Avail', models.BooleanField()),
                ('U_N', models.CharField(max_length=25)),
                ('P_W', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='General_Medicine',
            fields=[
                ('Disease', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Medicine', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_Id', models.CharField(max_length=25)),
                ('H_Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='latlng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Medical_shop',
            fields=[
                ('shop_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=255)),
                ('Lattitude', models.FloatField(default='NULL')),
                ('Longitude', models.FloatField(default='NULL')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='none', max_length=200)),
                ('Age', models.IntegerField(default=18)),
                ('Gender', models.CharField(max_length=10)),
                ('Blood_group', models.CharField(max_length=3)),
                ('medical_con', models.CharField(default='No Problems', max_length=255)),
                ('Phone_num', models.CharField(max_length=13)),
                ('Emergency_num', models.CharField(max_length=13)),
                ('PatientId', models.CharField(default='0', max_length=255)),
                ('Email_Id', models.CharField(default='NULL', max_length=255)),
                ('user', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Med_id', models.CharField(max_length=255)),
                ('Medicine_name', models.CharField(max_length=255)),
                ('Stock', models.IntegerField()),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Medical_shop')),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='H_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Hospital_Details'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='T_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Doctor_Type'),
        ),
        migrations.AddField(
            model_name='doctor_details',
            name='D_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Doctors'),
        ),
    ]
