# Generated by Django 2.1.3 on 2018-11-16 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_avail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_grp', models.CharField(max_length=255)),
                ('Availability', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Blood_Bank',
            fields=[
                ('BB_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('BB_name', models.CharField(max_length=255)),
                ('Lat', models.FloatField(default='NULL')),
                ('Long', models.FloatField(default='NULL')),
            ],
        ),
        migrations.CreateModel(
            name='textinblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor_details',
            name='D_Id',
        ),
        migrations.DeleteModel(
            name='latlng',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='P_W',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='U_N',
        ),
        migrations.RemoveField(
            model_name='patient_db',
            name='Email_Id',
        ),
        migrations.RemoveField(
            model_name='patient_db',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='patient_db',
            name='PatientId',
        ),
        migrations.RemoveField(
            model_name='patient_db',
            name='medical_con',
        ),
        migrations.RemoveField(
            model_name='patient_db',
            name='user',
        ),
        migrations.AddField(
            model_name='doctors',
            name='Degrees',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='doctors',
            name='Desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='Latitudes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='doctors',
            name='Longitudes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='doctors',
            name='Phone',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='doctors',
            name='gender',
            field=models.CharField(blank=True, default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='hospital_details',
            name='Phone1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient_db',
            name='Marital_Status',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='patient_db',
            name='P_Id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='Avail',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='D_Id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='H_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.Hospital_Details'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='T_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.Doctor_Type'),
        ),
        migrations.AlterField(
            model_name='hospital_details',
            name='H_Id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient_db',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient_db',
            name='Emergency_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient_db',
            name='Phone_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock_availability',
            name='shop_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='login.Medical_shop'),
        ),
        migrations.DeleteModel(
            name='Doctor_Details',
        ),
        migrations.AddField(
            model_name='textinblog',
            name='doctors',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='login.Doctors'),
        ),
        migrations.AddField(
            model_name='blood_avail',
            name='BB_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='login.Blood_Bank'),
        ),
    ]
