# Generated by Django 2.1.3 on 2018-11-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20181117_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_db',
            name='medical_con',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
