# Generated by Django 2.1.3 on 2018-11-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_patient_db_medical_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_db',
            name='user',
            field=models.CharField(default='no', max_length=4),
        ),
    ]
