# Generated by Django 2.1.3 on 2018-11-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_avail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_grp', models.CharField(max_length=255)),
                ('Availability', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Blood_Bank',
            fields=[
                ('BB_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('BB_name', models.CharField(max_length=255)),
                ('Lat', models.FloatField(default='NULL')),
                ('Long', models.FloatField(default='NULL')),
            ],
        ),
        migrations.CreateModel(
            name='General_Medicine',
            fields=[
                ('Disease', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Medicine', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_shop',
            fields=[
                ('shop_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=255)),
                ('Lattitude', models.FloatField(default='NULL')),
                ('Longitude', models.FloatField(default='NULL')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Med_id', models.CharField(max_length=255)),
                ('Medicine_name', models.CharField(max_length=255)),
                ('Stock', models.IntegerField()),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient_home.Medical_shop')),
            ],
        ),
        migrations.AddField(
            model_name='blood_avail',
            name='BB_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient_home.Blood_Bank'),
        ),
    ]
