# Generated by Django 2.1.2 on 2018-11-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_Name', models.CharField(max_length=50)),
                ('L_Name', models.CharField(max_length=50)),
                ('Degrees', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_Id', models.CharField(max_length=100)),
                ('Spec', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('D_Id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Avail', models.BooleanField()),
                ('U_N', models.CharField(max_length=25)),
                ('P_W', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_Id', models.CharField(max_length=25)),
                ('H_Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=10)),
                ('Blood_group', models.CharField(max_length=3)),
                ('Maritial_Status', models.CharField(max_length=3)),
                ('PatientId', models.CharField(default='0', max_length=255)),
                ('Email_Id', models.CharField(default='NULL', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='H_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Hospital_Details'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='T_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Doctor_Type'),
        ),
        migrations.AddField(
            model_name='doctor_details',
            name='D_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Doctors'),
        ),
    ]
