# Generated by Django 2.1.2 on 2018-11-12 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_avail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_grp', models.CharField(max_length=255)),
                ('Availability', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Blood_Bank',
            fields=[
                ('BB_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('BB_name', models.CharField(max_length=255)),
                ('Lat', models.FloatField(default='NULL')),
                ('Long', models.FloatField(default='NULL')),
            ],
        ),
        migrations.CreateModel(
            name='General_Medicine',
            fields=[
                ('Disease', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Medicine', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_shop',
            fields=[
                ('shop_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=255)),
                ('Lattitude', models.FloatField(default='NULL')),
                ('Longitude', models.FloatField(default='NULL')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Med_id', models.CharField(max_length=255)),
                ('Medicine_name', models.CharField(max_length=255)),
                ('Stock', models.IntegerField()),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Medical_shop')),
            ],
        ),
        migrations.CreateModel(
            name='textinblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='patient_db',
            old_name='Maritial_Status',
            new_name='Marital_Status',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='P_W',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='U_N',
        ),
        migrations.RemoveField(
            model_name='patient_db',
            name='Email_Id',
        ),
        migrations.RemoveField(
            model_name='patient_db',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='patient_db',
            name='PatientId',
        ),
        migrations.AddField(
            model_name='doctor_details',
            name='Desc',
            field=models.TextField(default='General Physician'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor_details',
            name='Latitudes',
            field=models.IntegerField(default='2222'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor_details',
            name='Longitudes',
            field=models.IntegerField(default='111'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor_details',
            name='Phone',
            field=models.IntegerField(default='1112321321'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='id',
            field=models.AutoField(auto_created=True, default='3213216354', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital_details',
            name='Phone1',
            field=models.IntegerField(default=323212),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital_details',
            name='Phone2',
            field=models.IntegerField(default=32132132),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital_details',
            name='Phone3',
            field=models.IntegerField(default=1321321321),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_db',
            name='Age',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_db',
            name='Emergency_num',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_db',
            name='P_Id',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient_db',
            name='Phone_num',
            field=models.IntegerField(default=132),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctors',
            name='D_Id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospital_details',
            name='H_Id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textinblog',
            name='D_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Doctors'),
        ),
        migrations.AddField(
            model_name='blood_avail',
            name='BB_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Blood_Bank'),
        ),
    ]
