# Generated by Django 2.1.2 on 2018-11-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181112_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textinblog',
            old_name='D_Id',
            new_name='Doctor',
        ),
    ]
