# Generated by Django 2.1.2 on 2018-11-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181112_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textinblog',
            old_name='Doctor',
            new_name='Doctors',
        ),
    ]
