# Generated by Django 2.1.2 on 2018-11-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181112_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textinblog',
            old_name='Doctors',
            new_name='doctors',
        ),
    ]
