# Generated by Django 2.1.2 on 2018-11-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DandS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='disease_part',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
