# Generated by Django 2.1.3 on 2018-11-17 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Blood_group', models.CharField(max_length=3)),
                ('medical_con', models.CharField(default='None', max_length=300)),
                ('Marital_Status', models.CharField(default='no', max_length=3)),
                ('user', models.CharField(default='no', max_length=4)),
                ('Phone_num', models.IntegerField()),
                ('Emergency_num', models.IntegerField()),
                ('P_Id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
