# Generated by Django 2.1.3 on 2018-11-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
