# Generated by Django 2.1.3 on 2018-11-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_patient_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_db',
            old_name='user',
            new_name='user_ava',
        ),
        migrations.RemoveField(
            model_name='patient_db',
            name='Marital_Status',
        ),
        migrations.AddField(
            model_name='patient_db',
            name='image_url',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='patient_db',
            name='Emergency_num',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='patient_db',
            name='Phone_num',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
