# Generated by Django 2.1.3 on 2018-11-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_auto_20181118_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_db',
            name='Age',
            field=models.CharField(max_length=3),
        ),
    ]
