# Generated by Django 2.1.3 on 2018-11-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_doctors_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Avail',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
