# Generated by Django 2.1.2 on 2018-10-31 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseidentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.TextField()),
            ],
        ),
    ]
