# Generated by Django 2.1.2 on 2018-11-05 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseidentification', '0002_tips'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_Medicine',
            fields=[
                ('Disease', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Medicine', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_shop',
            fields=[
                ('shop_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=255)),
                ('Lattitude', models.FloatField(default='NULL')),
                ('Longitude', models.FloatField(default='NULL')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Med_id', models.CharField(max_length=255)),
                ('Medicine_name', models.CharField(max_length=255)),
                ('Stock', models.IntegerField()),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diseaseidentification.Medical_shop')),
            ],
        ),
    ]
