# Generated by Django 2.1.2 on 2018-11-09 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseidentification', '0003_general_medicine_medical_shop_stock_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_avail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_grp', models.CharField(max_length=255)),
                ('Availability', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Blood_Bank',
            fields=[
                ('BB_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('BB_name', models.CharField(max_length=255)),
                ('Lat', models.FloatField(default='NULL')),
                ('Long', models.FloatField(default='NULL')),
            ],
        ),
        migrations.AddField(
            model_name='blood_avail',
            name='BB_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diseaseidentification.Blood_Bank'),
        ),
    ]
