# Generated by Django 2.1.2 on 2018-12-08 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Med_id', models.CharField(max_length=255)),
                ('Medicine_name', models.CharField(max_length=255)),
                ('Stock', models.IntegerField()),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Registration.Medical')),
            ],
        ),
    ]
