# Generated by Django 2.1.2 on 2018-12-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='Lattitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='medical',
            name='Longitude',
            field=models.FloatField(default=0),
        ),
    ]
